// db/seed-recipes.ts
// Seeds recipe bank with images from Pexels uploaded to UploadThing
// Run with: npx tsx db/seed-recipes.ts
//
// Required env vars in .env.local:
//   UPLOADTHING_TOKEN
//   PEXELS_API_KEY
//   DATABASE_URL (for Neon)
//
// Note: uses dotenvx to load .env.local — if you use a different loader,
// adjust the import below.

import dotenv from "dotenv";
const result = dotenv.config({ path: ".env.local" });
console.log("dotenv result:", result.error || "loaded OK");
console.log("DATABASE_URL exists:", !!process.env.DATABASE_URL);
import {
  seedRecipes,
  seedRecipeIngredients,
  seedRecipeInstructions,
} from "@/db/schema";
import { UTApi } from "uploadthing/server";
import { db } from ".";

// ============================================
// CONFIG
// ============================================
const PEXELS_API_KEY = process.env.PEXELS_API_KEY!;
const utapi = new UTApi();
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

// ============================================
// PEXELS IMAGE FETCHER
// ============================================
async function fetchPexelsImage(
  query: string,
): Promise<{ url: string; photographer: string } | null> {
  try {
    const res = await fetch(
      `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=3&orientation=landscape`,
      { headers: { Authorization: PEXELS_API_KEY } },
    );
    if (!res.ok) {
      console.warn(`  ⚠️  Pexels API error for "${query}": ${res.status}`);
      return null;
    }
    const data = await res.json();
    if (!data.photos?.length) {
      console.warn(`  ⚠️  No Pexels results for "${query}"`);
      return null;
    }
    const photo = data.photos[0];
    return { url: photo.src.large, photographer: photo.photographer };
  } catch (err) {
    console.warn(`  ⚠️  Pexels fetch failed for "${query}":`, err);
    return null;
  }
}

// ============================================
// UPLOAD TO UPLOADTHING
// ============================================
async function uploadToUploadThing(
  imageUrl: string,
  fileName: string,
): Promise<string | null> {
  try {
    const res = await fetch(imageUrl);
    if (!res.ok) return null;
    const blob = await res.blob();
    const file = new File([blob], `${fileName}.jpg`, { type: "image/jpeg" });
    const uploadResponse = await utapi.uploadFiles(file);
    if (uploadResponse.error) {
      console.warn(`  ⚠️  UploadThing error: ${uploadResponse.error.message}`);
      return null;
    }
    return uploadResponse.data.ufsUrl || uploadResponse.data.url;
  } catch (err) {
    console.warn(`  ⚠️  Upload failed for ${fileName}:`, err);
    return null;
  }
}

// ============================================
// TYPES
// ============================================
type SeedRecipe = {
  title: string;
  description: string;
  imageSearch: string;
  servings: number;
  prepTime: number;
  cookTime: number;
  totalTime: number;
  difficulty: "beginner" | "intermediate" | "advanced";
  cuisine: string;
  dietaryTags: string[];
  timeCategory: "quick" | "moderate" | "elaborate";
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  ingredients: { ingredient: string; amount: string }[];
  instructions: string[];
};

// ============================================
// RECIPE DATA (61 recipes)
// ============================================
const recipes: SeedRecipe[] = [
  // ---------- ITALIAN ----------
  {
    title: "Classic Margherita Pizza",
    description:
      "Simple and authentic Neapolitan-style pizza with fresh mozzarella and basil.",
    imageSearch: "margherita pizza fresh basil",
    servings: 4,
    prepTime: 20,
    cookTime: 12,
    totalTime: 32,
    difficulty: "intermediate",
    cuisine: "italian",
    dietaryTags: ["vegetarian"],
    timeCategory: "moderate",
    calories: 320,
    protein: 14,
    carbs: 38,
    fat: 12,
    ingredients: [
      { ingredient: "pizza dough", amount: "1 lb" },
      { ingredient: "San Marzano tomatoes", amount: "1 can (14 oz)" },
      { ingredient: "fresh mozzarella", amount: "8 oz" },
      { ingredient: "fresh basil leaves", amount: "1/4 cup" },
      { ingredient: "extra virgin olive oil", amount: "2 tbsp" },
      { ingredient: "salt", amount: "1 tsp" },
      { ingredient: "garlic", amount: "2 cloves" },
    ],
    instructions: [
      "Preheat oven to 500°F (260°C) with a pizza stone or inverted baking sheet inside.",
      "Crush San Marzano tomatoes by hand, mix with minced garlic, salt, and 1 tbsp olive oil.",
      "Stretch dough into a 12-inch round on a floured surface.",
      "Spread a thin layer of tomato sauce over the dough, leaving a 1-inch border.",
      "Tear mozzarella into pieces and distribute evenly over the pizza.",
      "Transfer to the hot stone and bake for 10-12 minutes until crust is golden and cheese is bubbly.",
      "Top with fresh basil and drizzle with remaining olive oil before serving.",
    ],
  },
  {
    title: "Spaghetti Aglio e Olio",
    description:
      "A quick Roman classic with garlic, olive oil, and red pepper flakes.",
    imageSearch: "spaghetti aglio olio garlic",
    servings: 4,
    prepTime: 5,
    cookTime: 15,
    totalTime: 20,
    difficulty: "beginner",
    cuisine: "italian",
    dietaryTags: ["vegan"],
    timeCategory: "quick",
    calories: 380,
    protein: 10,
    carbs: 52,
    fat: 14,
    ingredients: [
      { ingredient: "spaghetti", amount: "1 lb" },
      { ingredient: "garlic", amount: "6 cloves" },
      { ingredient: "extra virgin olive oil", amount: "1/3 cup" },
      { ingredient: "red pepper flakes", amount: "1/2 tsp" },
      { ingredient: "fresh parsley", amount: "1/4 cup" },
      { ingredient: "salt", amount: "to taste" },
    ],
    instructions: [
      "Bring a large pot of salted water to a boil. Cook spaghetti until al dente, reserving 1 cup pasta water.",
      "While pasta cooks, thinly slice garlic. Heat olive oil in a large skillet over medium-low heat.",
      "Add garlic and red pepper flakes, cooking until garlic is golden (about 2 minutes). Don't burn it.",
      "Add cooked pasta to the skillet with 1/2 cup pasta water. Toss vigorously to emulsify.",
      "Add more pasta water if needed. Toss in parsley, season with salt, and serve immediately.",
    ],
  },
  {
    title: "Chicken Parmigiana",
    description:
      "Crispy breaded chicken topped with marinara and melted mozzarella.",
    imageSearch: "chicken parmesan mozzarella",
    servings: 4,
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    difficulty: "intermediate",
    cuisine: "italian",
    dietaryTags: [],
    timeCategory: "moderate",
    calories: 520,
    protein: 42,
    carbs: 30,
    fat: 24,
    ingredients: [
      { ingredient: "chicken breasts", amount: "4 (6 oz each)" },
      { ingredient: "breadcrumbs", amount: "1 cup" },
      { ingredient: "parmesan cheese", amount: "1/2 cup grated" },
      { ingredient: "eggs", amount: "2" },
      { ingredient: "marinara sauce", amount: "2 cups" },
      { ingredient: "mozzarella cheese", amount: "1 cup shredded" },
      { ingredient: "olive oil", amount: "1/4 cup" },
      { ingredient: "salt and pepper", amount: "to taste" },
    ],
    instructions: [
      "Preheat oven to 425°F. Pound chicken breasts to even 1/2-inch thickness.",
      "Set up breading station: flour, beaten eggs, and breadcrumbs mixed with parmesan.",
      "Coat chicken in flour, dip in egg, then press into breadcrumb mixture.",
      "Heat olive oil in an oven-safe skillet. Pan-fry chicken 3-4 minutes per side until golden.",
      "Spoon marinara over each piece, top with mozzarella.",
      "Transfer to oven and bake 15 minutes until cheese is bubbly and chicken reaches 165°F.",
    ],
  },
  {
    title: "Risotto ai Funghi",
    description: "Creamy mushroom risotto with parmesan and fresh thyme.",
    imageSearch: "mushroom risotto parmesan",
    servings: 4,
    prepTime: 10,
    cookTime: 35,
    totalTime: 45,
    difficulty: "advanced",
    cuisine: "italian",
    dietaryTags: ["vegetarian", "gluten-free"],
    timeCategory: "moderate",
    calories: 410,
    protein: 12,
    carbs: 58,
    fat: 14,
    ingredients: [
      { ingredient: "arborio rice", amount: "1.5 cups" },
      { ingredient: "mixed mushrooms", amount: "12 oz" },
      { ingredient: "vegetable broth", amount: "6 cups" },
      { ingredient: "white wine", amount: "1/2 cup" },
      { ingredient: "onion", amount: "1 medium" },
      { ingredient: "parmesan cheese", amount: "1/2 cup grated" },
      { ingredient: "butter", amount: "2 tbsp" },
      { ingredient: "fresh thyme", amount: "1 tbsp" },
      { ingredient: "garlic", amount: "2 cloves" },
    ],
    instructions: [
      "Warm broth in a saucepan and keep at a gentle simmer.",
      "Sauté sliced mushrooms in butter until golden, about 5 minutes. Set aside.",
      "In the same pot, cook diced onion until soft. Add garlic and cook 1 minute.",
      "Add rice and stir for 2 minutes until edges are translucent.",
      "Pour in wine and stir until absorbed.",
      "Add warm broth one ladle at a time, stirring constantly, waiting until each addition is absorbed. This takes about 20 minutes.",
      "Fold in mushrooms, parmesan, thyme, and remaining butter. Season and serve immediately.",
    ],
  },
  {
    title: "Caprese Salad",
    description:
      "Fresh tomatoes, mozzarella, and basil drizzled with balsamic glaze.",
    imageSearch: "caprese salad fresh mozzarella tomato",
    servings: 2,
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    difficulty: "beginner",
    cuisine: "italian",
    dietaryTags: ["vegetarian", "gluten-free"],
    timeCategory: "quick",
    calories: 250,
    protein: 14,
    carbs: 8,
    fat: 18,
    ingredients: [
      { ingredient: "ripe tomatoes", amount: "3 large" },
      { ingredient: "fresh mozzarella", amount: "8 oz" },
      { ingredient: "fresh basil", amount: "1/4 cup" },
      { ingredient: "extra virgin olive oil", amount: "2 tbsp" },
      { ingredient: "balsamic glaze", amount: "1 tbsp" },
      { ingredient: "flaky sea salt", amount: "to taste" },
    ],
    instructions: [
      "Slice tomatoes and mozzarella into 1/4-inch rounds.",
      "Arrange alternating slices of tomato and mozzarella on a plate.",
      "Tuck basil leaves between slices.",
      "Drizzle with olive oil and balsamic glaze. Finish with flaky salt.",
    ],
  },
  {
    title: "Tomato Basil Bruschetta",
    description: "Fresh diced tomato topping on crispy garlic-rubbed bread.",
    imageSearch: "bruschetta tomato basil",
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    totalTime: 15,
    difficulty: "beginner",
    cuisine: "italian",
    dietaryTags: ["vegan"],
    timeCategory: "quick",
    calories: 180,
    protein: 4,
    carbs: 24,
    fat: 8,
    ingredients: [
      { ingredient: "baguette", amount: "1" },
      { ingredient: "ripe tomatoes", amount: "4" },
      { ingredient: "fresh basil", amount: "1/4 cup" },
      { ingredient: "garlic", amount: "3 cloves" },
      { ingredient: "extra virgin olive oil", amount: "2 tbsp" },
      { ingredient: "balsamic vinegar", amount: "1 tsp" },
    ],
    instructions: [
      "Dice tomatoes, mix with chopped basil, olive oil, balsamic, minced garlic, salt and pepper. Let sit 10 minutes.",
      "Slice baguette into 1/2-inch rounds. Brush with olive oil and toast until golden.",
      "Rub a cut garlic clove on each warm toast.",
      "Spoon tomato mixture generously on top. Serve immediately.",
    ],
  },
  {
    title: "Zucchini Noodle Shrimp Scampi",
    description:
      "Light and garlicky shrimp scampi over spiralized zucchini noodles.",
    imageSearch: "zucchini noodles shrimp scampi",
    servings: 4,
    prepTime: 10,
    cookTime: 10,
    totalTime: 20,
    difficulty: "beginner",
    cuisine: "italian",
    dietaryTags: ["keto", "gluten-free"],
    timeCategory: "quick",
    calories: 280,
    protein: 28,
    carbs: 8,
    fat: 16,
    ingredients: [
      { ingredient: "large shrimp", amount: "1.5 lbs peeled" },
      { ingredient: "zucchini", amount: "4 medium" },
      { ingredient: "garlic", amount: "5 cloves" },
      { ingredient: "butter", amount: "3 tbsp" },
      { ingredient: "white wine", amount: "1/4 cup" },
      { ingredient: "lemon", amount: "1" },
      { ingredient: "red pepper flakes", amount: "1/4 tsp" },
      { ingredient: "fresh parsley", amount: "2 tbsp" },
    ],
    instructions: [
      "Spiralize zucchini into noodles. Pat dry with paper towels.",
      "Melt 1 tbsp butter in a large skillet. Sauté zoodles 2 minutes until just tender. Remove and set aside.",
      "In the same pan, melt remaining butter. Add garlic and red pepper flakes, cook 30 seconds.",
      "Add shrimp in a single layer. Cook 2 minutes per side until pink.",
      "Pour in white wine and lemon juice. Let sauce reduce for 1 minute.",
      "Return zoodles to the pan, toss with shrimp. Garnish with parsley.",
    ],
  },
  {
    title: "15-Minute Garlic Shrimp Pasta",
    description:
      "Quick and impressive pasta with garlic butter shrimp and white wine.",
    imageSearch: "garlic shrimp pasta linguine",
    servings: 4,
    prepTime: 5,
    cookTime: 10,
    totalTime: 15,
    difficulty: "beginner",
    cuisine: "italian",
    dietaryTags: [],
    timeCategory: "quick",
    calories: 420,
    protein: 28,
    carbs: 48,
    fat: 14,
    ingredients: [
      { ingredient: "linguine", amount: "1 lb" },
      { ingredient: "large shrimp", amount: "1 lb peeled" },
      { ingredient: "garlic", amount: "6 cloves" },
      { ingredient: "butter", amount: "3 tbsp" },
      { ingredient: "white wine", amount: "1/4 cup" },
      { ingredient: "lemon", amount: "1" },
      { ingredient: "red pepper flakes", amount: "1/4 tsp" },
      { ingredient: "fresh parsley", amount: "3 tbsp" },
    ],
    instructions: [
      "Cook linguine in salted water until al dente. Reserve 1 cup pasta water.",
      "Melt butter in a large pan. Add sliced garlic and pepper flakes, cook 30 seconds.",
      "Add shrimp in a single layer, cook 2 minutes per side until pink.",
      "Pour in white wine and lemon juice. Let reduce 1 minute.",
      "Toss in pasta with a splash of pasta water. Toss until coated. Garnish with parsley.",
    ],
  },
  {
    title: "Homemade Pasta with Bolognese",
    description: "Fresh egg pasta with a slow-simmered, rich meat ragù.",
    imageSearch: "fresh pasta bolognese ragu",
    servings: 6,
    prepTime: 45,
    cookTime: 120,
    totalTime: 165,
    difficulty: "advanced",
    cuisine: "italian",
    dietaryTags: [],
    timeCategory: "elaborate",
    calories: 520,
    protein: 28,
    carbs: 52,
    fat: 22,
    ingredients: [
      { ingredient: "00 flour", amount: "3 cups" },
      { ingredient: "eggs", amount: "4" },
      { ingredient: "ground beef", amount: "1 lb" },
      { ingredient: "ground pork", amount: "1/2 lb" },
      { ingredient: "onion", amount: "1" },
      { ingredient: "carrot", amount: "1" },
      { ingredient: "celery", amount: "2 stalks" },
      { ingredient: "tomato paste", amount: "2 tbsp" },
      { ingredient: "crushed tomatoes", amount: "1 can (28 oz)" },
      { ingredient: "whole milk", amount: "1/2 cup" },
      { ingredient: "red wine", amount: "1/2 cup" },
      { ingredient: "parmesan", amount: "for serving" },
    ],
    instructions: [
      "Make pasta: mound flour, create a well, crack in eggs. Mix with a fork, then knead 10 minutes until smooth and elastic. Rest 30 minutes.",
      "Finely dice onion, carrot, and celery (soffritto). Sauté in olive oil until soft.",
      "Add ground beef and pork, breaking up. Cook until browned.",
      "Add tomato paste, cook 2 minutes. Pour in red wine and let it evaporate.",
      "Add crushed tomatoes and milk. Simmer on the lowest heat for 2 hours, stirring occasionally.",
      "Roll pasta thin and cut into tagliatelle. Cook in salted boiling water for 2-3 minutes.",
      "Toss fresh pasta with the ragù. Serve with grated parmesan.",
    ],
  },

  // ---------- MEXICAN ----------
  {
    title: "Street-Style Chicken Tacos",
    description:
      "Juicy seasoned chicken with fresh pico de gallo and cilantro-lime crema.",
    imageSearch: "street chicken tacos cilantro lime",
    servings: 4,
    prepTime: 15,
    cookTime: 12,
    totalTime: 27,
    difficulty: "beginner",
    cuisine: "mexican",
    dietaryTags: [],
    timeCategory: "quick",
    calories: 380,
    protein: 28,
    carbs: 32,
    fat: 14,
    ingredients: [
      { ingredient: "chicken thighs", amount: "1.5 lbs" },
      { ingredient: "corn tortillas", amount: "12 small" },
      { ingredient: "lime", amount: "2" },
      { ingredient: "cilantro", amount: "1/2 cup" },
      { ingredient: "white onion", amount: "1" },
      { ingredient: "tomatoes", amount: "2" },
      { ingredient: "jalapeño", amount: "1" },
      { ingredient: "cumin", amount: "1 tsp" },
      { ingredient: "chili powder", amount: "1 tsp" },
      { ingredient: "sour cream", amount: "1/4 cup" },
    ],
    instructions: [
      "Season chicken with cumin, chili powder, salt, and juice of 1 lime.",
      "Grill or pan-sear chicken over high heat, 5-6 minutes per side until charred and cooked through.",
      "Make pico: dice tomatoes, onion, jalapeño, and cilantro. Mix with lime juice and salt.",
      "Mix sour cream with lime juice and chopped cilantro for crema.",
      "Dice chicken into small pieces. Warm tortillas on a dry skillet.",
      "Assemble tacos with chicken, pico de gallo, and crema.",
    ],
  },
  {
    title: "Black Bean & Sweet Potato Enchiladas",
    description:
      "Hearty vegetarian enchiladas with roasted sweet potato and smoky chipotle sauce.",
    imageSearch: "enchiladas black bean sweet potato",
    servings: 4,
    prepTime: 20,
    cookTime: 35,
    totalTime: 55,
    difficulty: "intermediate",
    cuisine: "mexican",
    dietaryTags: ["vegetarian"],
    timeCategory: "moderate",
    calories: 420,
    protein: 16,
    carbs: 58,
    fat: 14,
    ingredients: [
      { ingredient: "sweet potatoes", amount: "2 large" },
      { ingredient: "black beans", amount: "1 can (15 oz)" },
      { ingredient: "flour tortillas", amount: "8 large" },
      { ingredient: "enchilada sauce", amount: "2 cups" },
      { ingredient: "Mexican cheese blend", amount: "1.5 cups" },
      { ingredient: "cumin", amount: "1 tsp" },
      { ingredient: "chipotle in adobo", amount: "2 peppers" },
      { ingredient: "onion", amount: "1" },
      { ingredient: "garlic", amount: "3 cloves" },
    ],
    instructions: [
      "Preheat oven to 400°F. Peel and dice sweet potatoes into 1/2-inch cubes.",
      "Toss sweet potatoes with oil, cumin, and salt. Roast 20 minutes until tender.",
      "Sauté diced onion and garlic. Add drained black beans and mashed chipotle peppers.",
      "Combine sweet potatoes with bean mixture. Reduce oven to 375°F.",
      "Spread 1/2 cup enchilada sauce in a baking dish. Fill tortillas with mixture and cheese, roll seam-side down.",
      "Pour remaining sauce over enchiladas, top with cheese. Bake 20 minutes until bubbly.",
    ],
  },
  {
    title: "Guacamole",
    description: "Classic chunky guacamole with fresh lime and serrano pepper.",
    imageSearch: "fresh guacamole avocado chips",
    servings: 4,
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    difficulty: "beginner",
    cuisine: "mexican",
    dietaryTags: ["vegan", "gluten-free"],
    timeCategory: "quick",
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 14,
    ingredients: [
      { ingredient: "ripe avocados", amount: "3" },
      { ingredient: "lime", amount: "1" },
      { ingredient: "red onion", amount: "1/4 cup diced" },
      { ingredient: "cilantro", amount: "3 tbsp" },
      { ingredient: "serrano pepper", amount: "1" },
      { ingredient: "tomato", amount: "1 small" },
      { ingredient: "salt", amount: "1/2 tsp" },
    ],
    instructions: [
      "Halve avocados and scoop into a bowl. Mash with a fork to desired consistency.",
      "Add lime juice and salt, mix well.",
      "Fold in diced onion, tomato, cilantro, and minced serrano pepper.",
      "Taste and adjust seasoning. Serve immediately with tortilla chips.",
    ],
  },
  {
    title: "Birria Tacos",
    description:
      "Tender braised beef in rich chile consommé, served in crispy dipped tortillas.",
    imageSearch: "birria tacos consomme",
    servings: 6,
    prepTime: 30,
    cookTime: 180,
    totalTime: 210,
    difficulty: "advanced",
    cuisine: "mexican",
    dietaryTags: [],
    timeCategory: "elaborate",
    calories: 480,
    protein: 38,
    carbs: 28,
    fat: 22,
    ingredients: [
      { ingredient: "beef chuck roast", amount: "3 lbs" },
      { ingredient: "guajillo chiles", amount: "6" },
      { ingredient: "ancho chiles", amount: "4" },
      { ingredient: "corn tortillas", amount: "18" },
      { ingredient: "onion", amount: "1 large" },
      { ingredient: "garlic", amount: "6 cloves" },
      { ingredient: "tomatoes", amount: "3" },
      { ingredient: "cumin", amount: "1 tbsp" },
      { ingredient: "oregano", amount: "1 tsp" },
      { ingredient: "apple cider vinegar", amount: "2 tbsp" },
      { ingredient: "beef broth", amount: "4 cups" },
      { ingredient: "Oaxaca cheese", amount: "1 cup" },
    ],
    instructions: [
      "Toast dried chiles in a dry pan until fragrant. Soak in hot water 20 minutes.",
      "Blend soaked chiles with roasted tomatoes, onion, garlic, cumin, oregano, and vinegar until smooth.",
      "Cut beef into large chunks, season generously with salt and pepper.",
      "In a Dutch oven, sear beef on all sides. Pour chile sauce and broth over meat.",
      "Cover and braise in a 325°F oven for 3 hours until meat shreds easily.",
      "Shred beef and return to the consommé. Skim fat from the broth.",
      "Dip corn tortillas in the consommé, griddle until crispy. Fill with shredded beef and cheese.",
      "Serve with a bowl of warm consommé for dipping, topped with diced onion and cilantro.",
    ],
  },
  {
    title: "Mexican Street Corn (Elote)",
    description:
      "Grilled corn slathered with crema, cotija cheese, and chili-lime seasoning.",
    imageSearch: "mexican elote street corn",
    servings: 4,
    prepTime: 5,
    cookTime: 10,
    totalTime: 15,
    difficulty: "beginner",
    cuisine: "mexican",
    dietaryTags: ["vegetarian", "gluten-free"],
    timeCategory: "quick",
    calories: 220,
    protein: 8,
    carbs: 28,
    fat: 10,
    ingredients: [
      { ingredient: "corn on the cob", amount: "4 ears" },
      { ingredient: "Mexican crema", amount: "1/4 cup" },
      { ingredient: "cotija cheese", amount: "1/2 cup crumbled" },
      { ingredient: "chili powder", amount: "1 tsp" },
      { ingredient: "lime", amount: "2" },
      { ingredient: "cilantro", amount: "2 tbsp" },
    ],
    instructions: [
      "Grill corn over high heat, turning occasionally, until charred in spots (about 10 minutes).",
      "Brush each ear generously with crema.",
      "Sprinkle with cotija cheese, chili powder, and chopped cilantro.",
      "Squeeze fresh lime juice over each ear. Serve immediately.",
    ],
  },
  {
    title: "Black Bean Burrito Bowl",
    description:
      "Loaded bowl with seasoned black beans, cilantro-lime rice, and all the fixings.",
    imageSearch: "burrito bowl black bean rice avocado",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "beginner",
    cuisine: "mexican",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "moderate",
    calories: 420,
    protein: 14,
    carbs: 68,
    fat: 10,
    ingredients: [
      { ingredient: "black beans", amount: "2 cans" },
      { ingredient: "rice", amount: "2 cups cooked" },
      { ingredient: "corn", amount: "1 cup" },
      { ingredient: "avocado", amount: "2" },
      { ingredient: "cherry tomatoes", amount: "1 cup halved" },
      { ingredient: "cilantro", amount: "1/4 cup" },
      { ingredient: "lime", amount: "2" },
      { ingredient: "cumin", amount: "1 tsp" },
      { ingredient: "chili powder", amount: "1 tsp" },
      { ingredient: "red onion", amount: "1/4 cup diced" },
    ],
    instructions: [
      "Cook rice and fluff with lime juice and chopped cilantro.",
      "Heat black beans with cumin, chili powder, garlic, and salt.",
      "Char corn in a dry skillet until slightly blackened.",
      "Assemble bowls: cilantro-lime rice, black beans, corn, sliced avocado, tomatoes, red onion.",
      "Squeeze lime over everything. Add hot sauce to taste.",
    ],
  },
  {
    title: "Chicken Tortilla Soup",
    description:
      "Smoky, spicy broth with shredded chicken, topped with crispy tortilla strips.",
    imageSearch: "chicken tortilla soup crispy",
    servings: 6,
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    difficulty: "intermediate",
    cuisine: "mexican",
    dietaryTags: ["gluten-free"],
    timeCategory: "moderate",
    calories: 320,
    protein: 28,
    carbs: 24,
    fat: 12,
    ingredients: [
      { ingredient: "chicken breast", amount: "1.5 lbs" },
      { ingredient: "chicken broth", amount: "6 cups" },
      { ingredient: "fire-roasted tomatoes", amount: "1 can (14 oz)" },
      { ingredient: "corn tortillas", amount: "6" },
      { ingredient: "onion", amount: "1" },
      { ingredient: "garlic", amount: "3 cloves" },
      { ingredient: "chipotle in adobo", amount: "2 peppers" },
      { ingredient: "cumin", amount: "1 tsp" },
      { ingredient: "avocado", amount: "1" },
      { ingredient: "lime", amount: "2" },
      { ingredient: "sour cream and cilantro", amount: "for topping" },
    ],
    instructions: [
      "Cut tortillas into strips. Toss with oil and bake at 400°F for 8-10 minutes until crispy.",
      "Sauté diced onion until soft. Add garlic, cumin, and chopped chipotles.",
      "Add broth and tomatoes. Bring to a boil.",
      "Add whole chicken breasts. Simmer 20 minutes until cooked through.",
      "Remove chicken, shred with forks, and return to pot.",
      "Serve topped with tortilla strips, avocado, sour cream, cilantro, and lime.",
    ],
  },

  // ---------- ASIAN ----------
  {
    title: "Chicken Stir-Fry with Vegetables",
    description: "Quick weeknight stir-fry with a savory soy-ginger sauce.",
    imageSearch: "chicken vegetable stir fry wok",
    servings: 4,
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    difficulty: "beginner",
    cuisine: "asian",
    dietaryTags: ["dairy-free"],
    timeCategory: "quick",
    calories: 340,
    protein: 30,
    carbs: 24,
    fat: 12,
    ingredients: [
      { ingredient: "chicken breast", amount: "1.5 lbs" },
      { ingredient: "broccoli florets", amount: "2 cups" },
      { ingredient: "bell pepper", amount: "2" },
      { ingredient: "snap peas", amount: "1 cup" },
      { ingredient: "soy sauce", amount: "3 tbsp" },
      { ingredient: "sesame oil", amount: "1 tbsp" },
      { ingredient: "fresh ginger", amount: "1 tbsp grated" },
      { ingredient: "garlic", amount: "3 cloves" },
      { ingredient: "cornstarch", amount: "1 tbsp" },
      { ingredient: "rice", amount: "2 cups cooked" },
    ],
    instructions: [
      "Slice chicken into thin strips. Toss with 1 tbsp soy sauce and cornstarch.",
      "Heat a wok or large skillet over high heat with oil until smoking.",
      "Stir-fry chicken in batches, 2-3 minutes until browned. Remove and set aside.",
      "Add broccoli, peppers, and snap peas. Stir-fry 3 minutes until crisp-tender.",
      "Return chicken to wok. Add remaining soy sauce, ginger, garlic, and sesame oil.",
      "Toss everything together for 1 minute. Serve over rice.",
    ],
  },
  {
    title: "Pad Thai",
    description:
      "Sweet, sour, and savory Thai rice noodles with shrimp and peanuts.",
    imageSearch: "pad thai shrimp noodles",
    servings: 4,
    prepTime: 20,
    cookTime: 10,
    totalTime: 30,
    difficulty: "intermediate",
    cuisine: "asian",
    dietaryTags: ["dairy-free"],
    timeCategory: "moderate",
    calories: 420,
    protein: 22,
    carbs: 52,
    fat: 14,
    ingredients: [
      { ingredient: "rice noodles", amount: "8 oz" },
      { ingredient: "shrimp", amount: "1 lb peeled" },
      { ingredient: "eggs", amount: "2" },
      { ingredient: "bean sprouts", amount: "1 cup" },
      { ingredient: "green onions", amount: "4" },
      { ingredient: "roasted peanuts", amount: "1/3 cup" },
      { ingredient: "tamarind paste", amount: "2 tbsp" },
      { ingredient: "fish sauce", amount: "2 tbsp" },
      { ingredient: "brown sugar", amount: "2 tbsp" },
      { ingredient: "lime", amount: "2" },
      { ingredient: "garlic", amount: "3 cloves" },
    ],
    instructions: [
      "Soak rice noodles in warm water for 20 minutes, then drain.",
      "Mix tamarind paste, fish sauce, brown sugar, and 2 tbsp water to make the sauce.",
      "Heat oil in a wok over high heat. Cook shrimp 2 minutes per side, remove.",
      "Scramble eggs in the wok, then push to the side.",
      "Add noodles and sauce, toss for 2-3 minutes until noodles are tender.",
      "Return shrimp, add bean sprouts and green onions. Toss to combine.",
      "Serve with crushed peanuts and lime wedges.",
    ],
  },
  {
    title: "Vegetable Fried Rice",
    description:
      "Quick fried rice with crispy vegetables and a soy-sesame sauce.",
    imageSearch: "vegetable fried rice wok",
    servings: 4,
    prepTime: 10,
    cookTime: 10,
    totalTime: 20,
    difficulty: "beginner",
    cuisine: "asian",
    dietaryTags: ["vegan", "dairy-free"],
    timeCategory: "quick",
    calories: 310,
    protein: 8,
    carbs: 48,
    fat: 10,
    ingredients: [
      { ingredient: "day-old rice", amount: "4 cups cooked" },
      { ingredient: "frozen peas and carrots", amount: "1 cup" },
      { ingredient: "green onions", amount: "4" },
      { ingredient: "garlic", amount: "3 cloves" },
      { ingredient: "soy sauce", amount: "3 tbsp" },
      { ingredient: "sesame oil", amount: "1 tbsp" },
      { ingredient: "vegetable oil", amount: "2 tbsp" },
    ],
    instructions: [
      "Heat vegetable oil in a wok over high heat until smoking.",
      "Add peas, carrots, and minced garlic. Stir-fry 2 minutes.",
      "Add rice, breaking up clumps. Spread in an even layer and let it crisp for 1 minute before stirring.",
      "Add soy sauce and toss everything together.",
      "Drizzle with sesame oil, top with sliced green onions, and serve.",
    ],
  },
  {
    title: "Korean Bibimbap",
    description:
      "Rice bowl topped with seasoned vegetables, gochujang, and a fried egg.",
    imageSearch: "bibimbap korean rice bowl egg",
    servings: 4,
    prepTime: 30,
    cookTime: 20,
    totalTime: 50,
    difficulty: "intermediate",
    cuisine: "asian",
    dietaryTags: ["vegetarian"],
    timeCategory: "moderate",
    calories: 450,
    protein: 18,
    carbs: 62,
    fat: 14,
    ingredients: [
      { ingredient: "short-grain rice", amount: "2 cups" },
      { ingredient: "spinach", amount: "4 cups" },
      { ingredient: "carrots", amount: "2 julienned" },
      { ingredient: "zucchini", amount: "1 sliced" },
      { ingredient: "bean sprouts", amount: "1 cup" },
      { ingredient: "shiitake mushrooms", amount: "4 oz" },
      { ingredient: "eggs", amount: "4" },
      { ingredient: "gochujang", amount: "3 tbsp" },
      { ingredient: "sesame oil", amount: "2 tbsp" },
      { ingredient: "soy sauce", amount: "1 tbsp" },
      { ingredient: "sesame seeds", amount: "1 tbsp" },
    ],
    instructions: [
      "Cook rice according to package directions.",
      "Blanch spinach, squeeze dry, and season with sesame oil and salt.",
      "Sauté each vegetable separately with a bit of sesame oil and salt.",
      "Fry eggs sunny-side up in a non-stick pan.",
      "Divide rice among 4 bowls. Arrange vegetables in sections on top.",
      "Place a fried egg in the center of each bowl.",
      "Serve with gochujang on the side. Mix everything together before eating.",
    ],
  },
  {
    title: "Thai Green Curry",
    description: "Fragrant coconut curry with vegetables and Thai basil.",
    imageSearch: "thai green curry coconut",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "intermediate",
    cuisine: "asian",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "moderate",
    calories: 380,
    protein: 10,
    carbs: 28,
    fat: 26,
    ingredients: [
      { ingredient: "green curry paste", amount: "3 tbsp" },
      { ingredient: "coconut milk", amount: "2 cans (14 oz each)" },
      { ingredient: "tofu", amount: "14 oz firm, cubed" },
      { ingredient: "Thai eggplant or zucchini", amount: "2 cups" },
      { ingredient: "bamboo shoots", amount: "1 can" },
      { ingredient: "Thai basil", amount: "1 cup" },
      { ingredient: "fish sauce or soy sauce", amount: "2 tbsp" },
      { ingredient: "palm sugar or brown sugar", amount: "1 tbsp" },
      { ingredient: "jasmine rice", amount: "2 cups cooked" },
    ],
    instructions: [
      "Scoop the thick cream from the top of the coconut milk into a pot over medium-high heat.",
      "Fry the cream for 2 minutes until it splits, then add green curry paste. Stir 1 minute until fragrant.",
      "Add remaining coconut milk, eggplant, and bamboo shoots. Simmer 10 minutes.",
      "Add tofu, soy sauce, and sugar. Cook 5 more minutes.",
      "Stir in Thai basil just before serving. Serve over jasmine rice.",
    ],
  },
  {
    title: "Japanese Miso Soup",
    description:
      "Comforting soup with silken tofu, wakame seaweed, and green onions.",
    imageSearch: "miso soup tofu japanese",
    servings: 4,
    prepTime: 5,
    cookTime: 10,
    totalTime: 15,
    difficulty: "beginner",
    cuisine: "asian",
    dietaryTags: ["vegan", "dairy-free"],
    timeCategory: "quick",
    calories: 80,
    protein: 6,
    carbs: 8,
    fat: 3,
    ingredients: [
      { ingredient: "white miso paste", amount: "3 tbsp" },
      { ingredient: "silken tofu", amount: "7 oz" },
      { ingredient: "dried wakame seaweed", amount: "1 tbsp" },
      { ingredient: "dashi stock (or water)", amount: "4 cups" },
      { ingredient: "green onions", amount: "2" },
    ],
    instructions: [
      "Bring dashi stock to a gentle simmer (do not boil).",
      "Soak wakame in warm water for 5 minutes, drain.",
      "Cut tofu into small cubes.",
      "Remove a ladle of broth and dissolve miso paste into it. Pour back into the pot.",
      "Add tofu and wakame. Heat through for 2 minutes (never boil miso).",
      "Serve topped with sliced green onions.",
    ],
  },
  {
    title: "Japanese Teriyaki Chicken",
    description: "Glossy teriyaki-glazed chicken thighs with steamed rice.",
    imageSearch: "teriyaki chicken rice bowl",
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    totalTime: 30,
    difficulty: "beginner",
    cuisine: "asian",
    dietaryTags: ["dairy-free"],
    timeCategory: "quick",
    calories: 380,
    protein: 32,
    carbs: 28,
    fat: 14,
    ingredients: [
      { ingredient: "chicken thighs", amount: "2 lbs boneless" },
      { ingredient: "soy sauce", amount: "1/4 cup" },
      { ingredient: "mirin", amount: "2 tbsp" },
      { ingredient: "sake or rice wine", amount: "2 tbsp" },
      { ingredient: "sugar", amount: "2 tbsp" },
      { ingredient: "ginger", amount: "1 tsp grated" },
      { ingredient: "sesame seeds", amount: "for garnish" },
      { ingredient: "steamed rice", amount: "for serving" },
    ],
    instructions: [
      "Mix soy sauce, mirin, sake, sugar, and ginger to make teriyaki sauce.",
      "Score chicken thighs lightly. Season with salt.",
      "Sear chicken skin-side down in a hot pan for 5 minutes until crispy.",
      "Flip and cook 3 minutes more. Pour teriyaki sauce over chicken.",
      "Simmer, basting frequently, until sauce is thick and glossy (about 5 minutes).",
      "Slice and serve over rice. Garnish with sesame seeds.",
    ],
  },
  {
    title: "Dan Dan Noodles",
    description:
      "Spicy Sichuan noodles with savory pork and numbing chili oil.",
    imageSearch: "dan dan noodles sichuan",
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    difficulty: "intermediate",
    cuisine: "asian",
    dietaryTags: ["dairy-free"],
    timeCategory: "quick",
    calories: 440,
    protein: 22,
    carbs: 48,
    fat: 18,
    ingredients: [
      { ingredient: "Chinese wheat noodles", amount: "12 oz" },
      { ingredient: "ground pork", amount: "8 oz" },
      { ingredient: "chili oil", amount: "3 tbsp" },
      { ingredient: "soy sauce", amount: "2 tbsp" },
      { ingredient: "Chinese sesame paste (or tahini)", amount: "2 tbsp" },
      { ingredient: "Sichuan peppercorns", amount: "1 tsp ground" },
      { ingredient: "garlic", amount: "3 cloves" },
      { ingredient: "green onions", amount: "4" },
      { ingredient: "Chinese black vinegar", amount: "1 tbsp" },
    ],
    instructions: [
      "Cook noodles according to package. Drain and divide among bowls.",
      "Mix chili oil, soy sauce, sesame paste, black vinegar, and Sichuan pepper for the sauce.",
      "Brown ground pork in a wok with garlic until crispy.",
      "Pour sauce over noodles in each bowl. Top with crispy pork and sliced green onions.",
      "Mix everything together before eating.",
    ],
  },
  {
    title: "Edamame Stir-Fry",
    description:
      "Quick high-protein stir-fry with edamame, tofu, and vegetables.",
    imageSearch: "edamame tofu stir fry",
    servings: 4,
    prepTime: 10,
    cookTime: 10,
    totalTime: 20,
    difficulty: "beginner",
    cuisine: "asian",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "quick",
    calories: 280,
    protein: 20,
    carbs: 18,
    fat: 14,
    ingredients: [
      { ingredient: "shelled edamame", amount: "2 cups" },
      { ingredient: "firm tofu", amount: "14 oz pressed and cubed" },
      { ingredient: "broccoli florets", amount: "2 cups" },
      { ingredient: "red bell pepper", amount: "1" },
      { ingredient: "soy sauce or tamari", amount: "2 tbsp" },
      { ingredient: "sesame oil", amount: "1 tbsp" },
      { ingredient: "garlic", amount: "3 cloves" },
      { ingredient: "ginger", amount: "1 tsp grated" },
    ],
    instructions: [
      "Press tofu and cut into cubes. Pan-fry in oil until golden on all sides. Set aside.",
      "Heat sesame oil in a wok. Stir-fry broccoli and bell pepper for 3 minutes.",
      "Add edamame, garlic, and ginger. Cook 2 minutes.",
      "Return tofu to wok. Add soy sauce and toss everything together. Serve over rice.",
    ],
  },
  {
    title: "Pho (Vietnamese Beef Noodle Soup)",
    description:
      "Aromatic beef broth with rice noodles, fresh herbs, and thinly sliced beef.",
    imageSearch: "pho vietnamese beef noodle soup",
    servings: 4,
    prepTime: 15,
    cookTime: 120,
    totalTime: 135,
    difficulty: "advanced",
    cuisine: "asian",
    dietaryTags: ["dairy-free", "gluten-free"],
    timeCategory: "elaborate",
    calories: 420,
    protein: 32,
    carbs: 48,
    fat: 10,
    ingredients: [
      { ingredient: "beef bones", amount: "3 lbs" },
      { ingredient: "beef sirloin", amount: "1 lb thinly sliced" },
      { ingredient: "rice noodles", amount: "8 oz" },
      { ingredient: "onion", amount: "2 large" },
      { ingredient: "ginger", amount: "4 inch piece" },
      { ingredient: "star anise", amount: "3" },
      { ingredient: "cinnamon stick", amount: "1" },
      { ingredient: "cloves", amount: "3" },
      { ingredient: "fish sauce", amount: "3 tbsp" },
      { ingredient: "bean sprouts", amount: "2 cups" },
      { ingredient: "Thai basil, lime, jalapeño", amount: "for serving" },
      { ingredient: "hoisin sauce and sriracha", amount: "for serving" },
    ],
    instructions: [
      "Char onion and ginger under a broiler or over an open flame until blackened.",
      "Toast star anise, cinnamon, and cloves in a dry pan until fragrant.",
      "In a large pot, cover beef bones with water. Bring to a boil and discard the water.",
      "Return bones to pot with 10 cups fresh water, charred onion, ginger, and toasted spices.",
      "Simmer uncovered for 2 hours, skimming occasionally. Strain broth. Season with fish sauce.",
      "Cook rice noodles according to package. Divide among bowls.",
      "Ladle boiling hot broth over noodles and raw beef slices (the hot broth cooks the beef).",
      "Serve with bean sprouts, Thai basil, lime wedges, and jalapeño slices.",
    ],
  },
  {
    title: "Thai Coconut Soup (Tom Kha Gai)",
    description: "Creamy coconut soup with chicken, galangal, and mushrooms.",
    imageSearch: "tom kha gai coconut soup thai",
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    totalTime: 30,
    difficulty: "intermediate",
    cuisine: "asian",
    dietaryTags: ["gluten-free", "dairy-free"],
    timeCategory: "moderate",
    calories: 320,
    protein: 24,
    carbs: 12,
    fat: 22,
    ingredients: [
      { ingredient: "coconut milk", amount: "2 cans (14 oz each)" },
      { ingredient: "chicken breast", amount: "1 lb sliced thin" },
      { ingredient: "mushrooms", amount: "8 oz sliced" },
      { ingredient: "galangal or ginger", amount: "6 slices" },
      { ingredient: "lemongrass", amount: "2 stalks" },
      { ingredient: "lime leaves", amount: "4" },
      { ingredient: "fish sauce", amount: "3 tbsp" },
      { ingredient: "lime juice", amount: "3 tbsp" },
      { ingredient: "Thai chilies", amount: "2-3" },
      { ingredient: "cilantro", amount: "for garnish" },
    ],
    instructions: [
      "Bruise lemongrass with the back of a knife. Bring coconut milk to a gentle simmer with lemongrass, galangal, and lime leaves.",
      "Simmer aromatics for 5 minutes to infuse flavor.",
      "Add sliced chicken and mushrooms. Cook 10 minutes until chicken is done.",
      "Remove from heat. Stir in fish sauce, lime juice, and smashed chilies.",
      "Serve in bowls garnished with cilantro.",
    ],
  },
  {
    title: "Thai Mango Salad",
    description:
      "Crunchy green mango salad with peanuts, herbs, and spicy lime dressing.",
    imageSearch: "thai green mango salad peanuts",
    servings: 4,
    prepTime: 15,
    cookTime: 0,
    totalTime: 15,
    difficulty: "beginner",
    cuisine: "asian",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "quick",
    calories: 180,
    protein: 4,
    carbs: 22,
    fat: 10,
    ingredients: [
      { ingredient: "green (unripe) mango", amount: "2" },
      { ingredient: "carrots", amount: "1 shredded" },
      { ingredient: "red cabbage", amount: "1 cup shredded" },
      { ingredient: "roasted peanuts", amount: "1/4 cup" },
      { ingredient: "Thai basil and mint", amount: "1/4 cup each" },
      { ingredient: "lime juice", amount: "3 tbsp" },
      { ingredient: "palm sugar or brown sugar", amount: "1 tbsp" },
      { ingredient: "soy sauce", amount: "1 tbsp" },
      { ingredient: "Thai chili", amount: "1" },
    ],
    instructions: [
      "Julienne the green mango into thin matchsticks.",
      "Toss mango with shredded carrot and cabbage.",
      "Make dressing: whisk lime juice, sugar, soy sauce, and minced chili.",
      "Pour dressing over salad and toss. Top with crushed peanuts and torn herbs.",
    ],
  },
  {
    title: "Mango Sticky Rice",
    description:
      "Sweet Thai dessert with coconut-soaked sticky rice and fresh mango.",
    imageSearch: "mango sticky rice thai dessert",
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    totalTime: 35,
    difficulty: "beginner",
    cuisine: "asian",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "moderate",
    calories: 340,
    protein: 4,
    carbs: 68,
    fat: 8,
    ingredients: [
      { ingredient: "glutinous (sticky) rice", amount: "1.5 cups" },
      { ingredient: "coconut milk", amount: "1 can (14 oz)" },
      { ingredient: "sugar", amount: "1/4 cup" },
      { ingredient: "salt", amount: "1/4 tsp" },
      { ingredient: "ripe mangoes", amount: "2" },
      { ingredient: "sesame seeds", amount: "for garnish" },
    ],
    instructions: [
      "Soak sticky rice in water for at least 4 hours (overnight is best). Drain.",
      "Steam rice in a steamer basket lined with cheesecloth for 20-25 minutes until translucent.",
      "While rice steams, heat half the coconut milk with sugar and salt until dissolved.",
      "Pour the sweet coconut mixture over the hot rice. Stir and let it absorb for 15 minutes.",
      "Slice mangoes. Serve rice with mango slices and a drizzle of remaining coconut milk.",
    ],
  },

  // ---------- MEDITERRANEAN ----------
  {
    title: "Greek Chicken Souvlaki",
    description: "Lemon-herb marinated chicken skewers with tzatziki sauce.",
    imageSearch: "chicken souvlaki skewers tzatziki",
    servings: 4,
    prepTime: 20,
    cookTime: 12,
    totalTime: 32,
    difficulty: "beginner",
    cuisine: "mediterranean",
    dietaryTags: ["gluten-free"],
    timeCategory: "moderate",
    calories: 320,
    protein: 36,
    carbs: 6,
    fat: 16,
    ingredients: [
      { ingredient: "chicken breast", amount: "2 lbs" },
      { ingredient: "lemon", amount: "2" },
      { ingredient: "olive oil", amount: "3 tbsp" },
      { ingredient: "garlic", amount: "4 cloves" },
      { ingredient: "dried oregano", amount: "2 tsp" },
      { ingredient: "Greek yogurt", amount: "1 cup" },
      { ingredient: "cucumber", amount: "1" },
      { ingredient: "fresh dill", amount: "2 tbsp" },
      { ingredient: "pita bread", amount: "4" },
    ],
    instructions: [
      "Cut chicken into 1-inch cubes. Marinate in lemon juice, olive oil, garlic, and oregano for at least 30 minutes.",
      "Thread chicken onto skewers.",
      "Make tzatziki: grate cucumber and squeeze dry. Mix with yogurt, garlic, dill, lemon juice, and salt.",
      "Grill skewers over medium-high heat, 4-5 minutes per side until charred.",
      "Serve with warm pita bread and tzatziki sauce.",
    ],
  },
  {
    title: "Falafel Bowl",
    description:
      "Crispy baked falafel with hummus, tabbouleh, and pickled vegetables.",
    imageSearch: "falafel bowl hummus tabbouleh",
    servings: 4,
    prepTime: 25,
    cookTime: 25,
    totalTime: 50,
    difficulty: "intermediate",
    cuisine: "mediterranean",
    dietaryTags: ["vegan", "dairy-free"],
    timeCategory: "moderate",
    calories: 420,
    protein: 16,
    carbs: 52,
    fat: 18,
    ingredients: [
      { ingredient: "canned chickpeas", amount: "2 cans (15 oz each)" },
      { ingredient: "fresh parsley", amount: "1 cup" },
      { ingredient: "cilantro", amount: "1/2 cup" },
      { ingredient: "garlic", amount: "4 cloves" },
      { ingredient: "cumin", amount: "2 tsp" },
      { ingredient: "flour", amount: "2 tbsp" },
      { ingredient: "hummus", amount: "1 cup" },
      { ingredient: "cucumber", amount: "1" },
      { ingredient: "tomatoes", amount: "2" },
      { ingredient: "bulgur wheat", amount: "1 cup" },
      { ingredient: "lemon", amount: "2" },
    ],
    instructions: [
      "Preheat oven to 375°F. Drain chickpeas and pat very dry.",
      "Pulse chickpeas, parsley, cilantro, garlic, cumin, and flour in a food processor until coarse.",
      "Form into small patties. Place on an oiled baking sheet.",
      "Bake 25 minutes, flipping halfway, until golden and crispy.",
      "Cook bulgur. Toss with diced cucumber, tomato, parsley, lemon juice, and olive oil.",
      "Assemble bowls: tabbouleh base, falafel, hummus, and pickled onions.",
    ],
  },
  {
    title: "Shakshuka",
    description:
      "Eggs poached in spiced tomato-pepper sauce — a one-pan breakfast favorite.",
    imageSearch: "shakshuka eggs tomato sauce",
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    totalTime: 35,
    difficulty: "beginner",
    cuisine: "mediterranean",
    dietaryTags: ["vegetarian", "gluten-free"],
    timeCategory: "moderate",
    calories: 280,
    protein: 16,
    carbs: 18,
    fat: 16,
    ingredients: [
      { ingredient: "eggs", amount: "6" },
      { ingredient: "canned crushed tomatoes", amount: "1 can (28 oz)" },
      { ingredient: "red bell pepper", amount: "1" },
      { ingredient: "onion", amount: "1" },
      { ingredient: "garlic", amount: "3 cloves" },
      { ingredient: "cumin", amount: "1 tsp" },
      { ingredient: "paprika", amount: "1 tsp" },
      { ingredient: "cayenne pepper", amount: "1/4 tsp" },
      { ingredient: "feta cheese", amount: "1/4 cup crumbled" },
      { ingredient: "fresh cilantro", amount: "for garnish" },
    ],
    instructions: [
      "Heat olive oil in a large skillet. Sauté diced onion and bell pepper until soft.",
      "Add garlic, cumin, paprika, and cayenne. Cook 1 minute until fragrant.",
      "Pour in crushed tomatoes, season with salt. Simmer 10 minutes until thickened.",
      "Make 6 wells in the sauce. Crack an egg into each well.",
      "Cover and cook 6-8 minutes until whites are set but yolks are still runny.",
      "Top with crumbled feta and cilantro. Serve with crusty bread.",
    ],
  },
  {
    title: "Lamb Kofta Kebabs",
    description: "Spiced ground lamb skewers with mint yogurt sauce.",
    imageSearch: "lamb kofta kebab mint yogurt",
    servings: 4,
    prepTime: 20,
    cookTime: 10,
    totalTime: 30,
    difficulty: "intermediate",
    cuisine: "mediterranean",
    dietaryTags: ["gluten-free"],
    timeCategory: "moderate",
    calories: 380,
    protein: 28,
    carbs: 4,
    fat: 28,
    ingredients: [
      { ingredient: "ground lamb", amount: "1.5 lbs" },
      { ingredient: "onion", amount: "1 grated" },
      { ingredient: "garlic", amount: "3 cloves" },
      { ingredient: "cumin", amount: "2 tsp" },
      { ingredient: "coriander", amount: "1 tsp" },
      { ingredient: "cinnamon", amount: "1/2 tsp" },
      { ingredient: "fresh parsley", amount: "1/4 cup" },
      { ingredient: "Greek yogurt", amount: "1 cup" },
      { ingredient: "fresh mint", amount: "3 tbsp" },
    ],
    instructions: [
      "Mix lamb with grated onion, garlic, cumin, coriander, cinnamon, parsley, salt, and pepper.",
      "Form mixture around skewers into oval shapes.",
      "Make mint sauce: mix yogurt with chopped mint, lemon juice, and salt.",
      "Grill kofta over medium-high heat, 4-5 minutes per side.",
      "Serve with mint yogurt, warm pita, and a simple salad.",
    ],
  },
  {
    title: "Roasted Cauliflower Steaks",
    description: "Thick-cut cauliflower roasted until golden with chimichurri.",
    imageSearch: "roasted cauliflower steak chimichurri",
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    difficulty: "beginner",
    cuisine: "mediterranean",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "moderate",
    calories: 180,
    protein: 6,
    carbs: 16,
    fat: 12,
    ingredients: [
      { ingredient: "cauliflower heads", amount: "2 large" },
      { ingredient: "olive oil", amount: "3 tbsp" },
      { ingredient: "smoked paprika", amount: "1 tsp" },
      { ingredient: "fresh parsley", amount: "1 cup" },
      { ingredient: "fresh oregano", amount: "2 tbsp" },
      { ingredient: "red wine vinegar", amount: "2 tbsp" },
      { ingredient: "garlic", amount: "4 cloves" },
      { ingredient: "red pepper flakes", amount: "1/4 tsp" },
    ],
    instructions: [
      "Preheat oven to 425°F. Slice cauliflower into 1-inch thick steaks.",
      "Brush with olive oil, season with smoked paprika, salt, and pepper.",
      "Roast 25-30 minutes, flipping once, until golden and tender.",
      "Make chimichurri: chop parsley, oregano, garlic. Mix with vinegar, olive oil, red pepper flakes.",
      "Spoon chimichurri generously over roasted cauliflower steaks.",
    ],
  },
  {
    title: "One-Pan Lemon Herb Chicken & Vegetables",
    description:
      "Sheet pan dinner with chicken thighs, potatoes, and seasonal vegetables.",
    imageSearch: "sheet pan lemon chicken vegetables",
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    difficulty: "beginner",
    cuisine: "mediterranean",
    dietaryTags: ["gluten-free", "dairy-free"],
    timeCategory: "moderate",
    calories: 380,
    protein: 32,
    carbs: 28,
    fat: 16,
    ingredients: [
      { ingredient: "chicken thighs", amount: "8 bone-in" },
      { ingredient: "baby potatoes", amount: "1 lb halved" },
      { ingredient: "zucchini", amount: "2" },
      { ingredient: "cherry tomatoes", amount: "1 cup" },
      { ingredient: "lemon", amount: "1" },
      { ingredient: "dried oregano", amount: "2 tsp" },
      { ingredient: "garlic", amount: "4 cloves" },
      { ingredient: "olive oil", amount: "3 tbsp" },
    ],
    instructions: [
      "Preheat oven to 425°F. Toss potatoes with olive oil, salt, and pepper on a sheet pan.",
      "Roast potatoes alone for 10 minutes to get a head start.",
      "Toss chicken with olive oil, oregano, minced garlic, lemon juice, salt, and pepper.",
      "Add chicken to the pan with potatoes. Scatter zucchini and tomatoes around.",
      "Roast 25-30 minutes until chicken skin is crispy and internal temp reaches 165°F.",
    ],
  },
  {
    title: "Mediterranean Quinoa Salad",
    description:
      "Protein-packed grain salad with cucumber, feta, olives, and lemon dressing.",
    imageSearch: "mediterranean quinoa salad feta",
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    totalTime: 30,
    difficulty: "beginner",
    cuisine: "mediterranean",
    dietaryTags: ["vegetarian", "gluten-free"],
    timeCategory: "quick",
    calories: 340,
    protein: 12,
    carbs: 38,
    fat: 16,
    ingredients: [
      { ingredient: "quinoa", amount: "1.5 cups" },
      { ingredient: "cucumber", amount: "1 large diced" },
      { ingredient: "cherry tomatoes", amount: "1 cup halved" },
      { ingredient: "kalamata olives", amount: "1/2 cup" },
      { ingredient: "red onion", amount: "1/4 cup diced" },
      { ingredient: "feta cheese", amount: "1/2 cup crumbled" },
      { ingredient: "lemon", amount: "2" },
      { ingredient: "olive oil", amount: "3 tbsp" },
      { ingredient: "fresh mint and parsley", amount: "1/4 cup each" },
    ],
    instructions: [
      "Cook quinoa according to package. Fluff and let cool completely.",
      "Whisk lemon juice, olive oil, salt, and pepper for the dressing.",
      "Toss cooled quinoa with cucumber, tomatoes, olives, onion, and herbs.",
      "Pour dressing over and toss. Top with crumbled feta.",
      "Best served at room temperature. Keeps well for 3 days.",
    ],
  },

  // ---------- INDIAN ----------
  {
    title: "Butter Chicken (Murgh Makhani)",
    description: "Rich and creamy tomato-based chicken curry with warm spices.",
    imageSearch: "butter chicken curry naan",
    servings: 4,
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    difficulty: "intermediate",
    cuisine: "indian",
    dietaryTags: ["gluten-free"],
    timeCategory: "moderate",
    calories: 420,
    protein: 34,
    carbs: 16,
    fat: 24,
    ingredients: [
      { ingredient: "chicken thighs", amount: "2 lbs boneless" },
      { ingredient: "yogurt", amount: "1/2 cup" },
      { ingredient: "tomato passata", amount: "2 cups" },
      { ingredient: "heavy cream", amount: "1/2 cup" },
      { ingredient: "butter", amount: "3 tbsp" },
      { ingredient: "onion", amount: "1 large" },
      { ingredient: "garlic", amount: "4 cloves" },
      { ingredient: "ginger", amount: "1 inch piece" },
      { ingredient: "garam masala", amount: "2 tsp" },
      { ingredient: "turmeric", amount: "1 tsp" },
      { ingredient: "cumin", amount: "1 tsp" },
      { ingredient: "kashmiri chili powder", amount: "1 tsp" },
      { ingredient: "basmati rice", amount: "2 cups" },
    ],
    instructions: [
      "Marinate chicken in yogurt, turmeric, chili powder, and salt for at least 30 minutes.",
      "Melt butter and sauté diced onion until golden.",
      "Add garlic-ginger paste, cook 1 minute. Add garam masala and cumin.",
      "Pour in tomato passata and simmer 15 minutes until thickened.",
      "Grill or pan-sear marinated chicken until charred. Cut into pieces.",
      "Add chicken to the sauce. Stir in cream and simmer 10 minutes.",
      "Serve over basmati rice with naan bread.",
    ],
  },
  {
    title: "Chana Masala",
    description:
      "Spiced chickpea curry with tomatoes — hearty and completely plant-based.",
    imageSearch: "chana masala chickpea curry",
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    totalTime: 35,
    difficulty: "beginner",
    cuisine: "indian",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "moderate",
    calories: 310,
    protein: 14,
    carbs: 48,
    fat: 8,
    ingredients: [
      { ingredient: "chickpeas", amount: "2 cans (15 oz each)" },
      { ingredient: "diced tomatoes", amount: "1 can (14 oz)" },
      { ingredient: "onion", amount: "1 large" },
      { ingredient: "garlic", amount: "4 cloves" },
      { ingredient: "ginger", amount: "1 inch piece" },
      { ingredient: "garam masala", amount: "2 tsp" },
      { ingredient: "cumin seeds", amount: "1 tsp" },
      { ingredient: "turmeric", amount: "1/2 tsp" },
      { ingredient: "coriander powder", amount: "1 tsp" },
      { ingredient: "lemon", amount: "1" },
      { ingredient: "cilantro", amount: "for garnish" },
    ],
    instructions: [
      "Heat oil. Add cumin seeds and let them sizzle for 30 seconds.",
      "Add diced onion and cook until golden brown, about 8 minutes.",
      "Add garlic-ginger paste, turmeric, coriander, and garam masala. Cook 1 minute.",
      "Pour in diced tomatoes and simmer 5 minutes.",
      "Add drained chickpeas and 1/2 cup water. Simmer 15 minutes.",
      "Squeeze lemon juice, garnish with cilantro. Serve with rice or naan.",
    ],
  },
  {
    title: "Dal Tadka",
    description: "Comforting red lentil stew with a tempered spice garnish.",
    imageSearch: "dal tadka lentil curry",
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    difficulty: "beginner",
    cuisine: "indian",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "moderate",
    calories: 280,
    protein: 16,
    carbs: 42,
    fat: 6,
    ingredients: [
      { ingredient: "red lentils", amount: "1.5 cups" },
      { ingredient: "onion", amount: "1" },
      { ingredient: "tomatoes", amount: "2" },
      { ingredient: "garlic", amount: "4 cloves" },
      { ingredient: "ginger", amount: "1 inch" },
      { ingredient: "turmeric", amount: "1/2 tsp" },
      { ingredient: "cumin seeds", amount: "1 tsp" },
      { ingredient: "mustard seeds", amount: "1/2 tsp" },
      { ingredient: "dried red chiles", amount: "2" },
      { ingredient: "ghee or oil", amount: "2 tbsp" },
      { ingredient: "cilantro", amount: "for garnish" },
    ],
    instructions: [
      "Wash lentils. Boil with turmeric and 4 cups water until soft, about 20 minutes. Mash lightly.",
      "In a separate pan, heat ghee/oil. Add cumin seeds, mustard seeds, and dried chiles — let them sizzle.",
      "Add sliced garlic and cook until golden. Add diced tomatoes and cook 5 minutes.",
      "Pour the tempered spice mixture (tadka) over the cooked lentils.",
      "Garnish with cilantro and serve with rice or roti.",
    ],
  },
  {
    title: "Chicken Tikka Masala",
    description: "Tandoori-spiced chicken in a rich, creamy tomato sauce.",
    imageSearch: "chicken tikka masala rice",
    servings: 4,
    prepTime: 25,
    cookTime: 30,
    totalTime: 55,
    difficulty: "advanced",
    cuisine: "indian",
    dietaryTags: [],
    timeCategory: "moderate",
    calories: 460,
    protein: 36,
    carbs: 18,
    fat: 26,
    ingredients: [
      { ingredient: "chicken breast", amount: "2 lbs" },
      { ingredient: "yogurt", amount: "1 cup" },
      { ingredient: "tomato passata", amount: "2 cups" },
      { ingredient: "heavy cream", amount: "1/2 cup" },
      { ingredient: "onion", amount: "2" },
      { ingredient: "garlic", amount: "6 cloves" },
      { ingredient: "ginger", amount: "2 inch piece" },
      { ingredient: "garam masala", amount: "2 tsp" },
      { ingredient: "tandoori masala", amount: "2 tbsp" },
      { ingredient: "cumin", amount: "1 tsp" },
      { ingredient: "paprika", amount: "1 tsp" },
      { ingredient: "butter", amount: "2 tbsp" },
      { ingredient: "kasuri methi (dried fenugreek)", amount: "1 tsp" },
    ],
    instructions: [
      "Cube chicken and marinate in yogurt, tandoori masala, and salt for at least 1 hour.",
      "Thread chicken onto skewers and broil or grill until charred.",
      "Melt butter, sauté diced onions until golden. Add garlic-ginger paste.",
      "Add cumin, paprika, and garam masala. Cook 1 minute.",
      "Pour in tomato passata. Simmer 15 minutes, then blend until smooth.",
      "Return sauce to pot. Add cream and crushed kasuri methi. Simmer 5 minutes.",
      "Add grilled chicken pieces to the sauce. Serve over basmati rice.",
    ],
  },
  {
    title: "Coconut Chickpea Curry",
    description:
      "Creamy one-pot curry that's rich, warming, and completely plant-based.",
    imageSearch: "coconut chickpea curry spinach",
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    totalTime: 35,
    difficulty: "beginner",
    cuisine: "indian",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "moderate",
    calories: 340,
    protein: 12,
    carbs: 38,
    fat: 16,
    ingredients: [
      { ingredient: "chickpeas", amount: "2 cans" },
      { ingredient: "coconut milk", amount: "1 can (14 oz)" },
      { ingredient: "diced tomatoes", amount: "1 can" },
      { ingredient: "spinach", amount: "3 cups" },
      { ingredient: "onion", amount: "1" },
      { ingredient: "garlic", amount: "3 cloves" },
      { ingredient: "curry powder", amount: "2 tbsp" },
      { ingredient: "ginger", amount: "1 tsp grated" },
      { ingredient: "rice", amount: "for serving" },
    ],
    instructions: [
      "Sauté diced onion until soft. Add garlic, ginger, and curry powder. Cook 1 minute.",
      "Add diced tomatoes and coconut milk. Bring to a simmer.",
      "Add drained chickpeas. Simmer 20 minutes until sauce thickens.",
      "Stir in spinach until wilted. Season with salt and serve over rice.",
    ],
  },
  {
    title: "Palak Paneer",
    description: "Creamy spinach curry with cubes of soft paneer cheese.",
    imageSearch: "palak paneer spinach curry",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "intermediate",
    cuisine: "indian",
    dietaryTags: ["vegetarian", "gluten-free"],
    timeCategory: "moderate",
    calories: 320,
    protein: 18,
    carbs: 14,
    fat: 22,
    ingredients: [
      { ingredient: "paneer", amount: "14 oz cubed" },
      { ingredient: "fresh spinach", amount: "1 lb" },
      { ingredient: "onion", amount: "1" },
      { ingredient: "garlic", amount: "4 cloves" },
      { ingredient: "ginger", amount: "1 inch" },
      { ingredient: "green chili", amount: "1" },
      { ingredient: "cumin seeds", amount: "1 tsp" },
      { ingredient: "garam masala", amount: "1 tsp" },
      { ingredient: "cream", amount: "2 tbsp" },
      { ingredient: "butter or ghee", amount: "2 tbsp" },
    ],
    instructions: [
      "Blanch spinach for 2 minutes. Ice bath, squeeze dry, and blend into a smooth paste.",
      "Heat butter. Add cumin seeds and let them sizzle.",
      "Add diced onion, cook until golden. Add garlic-ginger paste and green chili.",
      "Add spinach puree and garam masala. Simmer 5 minutes.",
      "Gently fold in paneer cubes. Cook 3 minutes.",
      "Stir in cream. Serve with naan or rice.",
    ],
  },

  // ---------- AMERICAN ----------
  {
    title: "Classic Smash Burger",
    description:
      "Crispy-edged thin patties with melted American cheese and special sauce.",
    imageSearch: "smash burger crispy cheese",
    servings: 4,
    prepTime: 10,
    cookTime: 8,
    totalTime: 18,
    difficulty: "beginner",
    cuisine: "american",
    dietaryTags: [],
    timeCategory: "quick",
    calories: 520,
    protein: 30,
    carbs: 34,
    fat: 30,
    ingredients: [
      { ingredient: "ground beef (80/20)", amount: "1.5 lbs" },
      { ingredient: "American cheese", amount: "8 slices" },
      { ingredient: "brioche buns", amount: "4" },
      { ingredient: "pickles", amount: "1/2 cup sliced" },
      { ingredient: "onion", amount: "1 small" },
      { ingredient: "mayonnaise", amount: "3 tbsp" },
      { ingredient: "ketchup", amount: "1 tbsp" },
      { ingredient: "mustard", amount: "1 tsp" },
      { ingredient: "pickle relish", amount: "1 tbsp" },
    ],
    instructions: [
      "Mix mayo, ketchup, mustard, and relish to make special sauce.",
      "Divide beef into 8 balls (about 3 oz each). Season with salt and pepper.",
      "Heat a cast iron skillet over high heat until smoking.",
      "Place a ball on the griddle and immediately smash flat. Season the top.",
      "Cook 2-3 minutes until edges are deeply crispy. Flip, add cheese, cook 1 minute.",
      "Toast buns. Assemble: sauce, double patties with cheese, pickles, onion.",
    ],
  },
  {
    title: "BBQ Pulled Pork",
    description: "Slow-cooked tender pulled pork with tangy barbecue sauce.",
    imageSearch: "bbq pulled pork sandwich coleslaw",
    servings: 8,
    prepTime: 15,
    cookTime: 480,
    totalTime: 495,
    difficulty: "intermediate",
    cuisine: "american",
    dietaryTags: ["dairy-free"],
    timeCategory: "elaborate",
    calories: 380,
    protein: 32,
    carbs: 28,
    fat: 16,
    ingredients: [
      { ingredient: "pork shoulder", amount: "4 lbs" },
      { ingredient: "BBQ sauce", amount: "2 cups" },
      { ingredient: "apple cider vinegar", amount: "1/4 cup" },
      { ingredient: "brown sugar", amount: "2 tbsp" },
      { ingredient: "paprika", amount: "2 tsp" },
      { ingredient: "garlic powder", amount: "1 tsp" },
      { ingredient: "onion powder", amount: "1 tsp" },
      { ingredient: "cayenne", amount: "1/2 tsp" },
      { ingredient: "brioche buns", amount: "8" },
      { ingredient: "coleslaw", amount: "for serving" },
    ],
    instructions: [
      "Mix paprika, garlic powder, onion powder, brown sugar, cayenne, salt, and pepper for the rub.",
      "Rub the spice mixture all over the pork shoulder.",
      "Place in a slow cooker. Pour apple cider vinegar around the meat.",
      "Cook on low for 8 hours until the meat falls apart.",
      "Shred the pork with two forks. Discard excess liquid.",
      "Mix shredded pork with BBQ sauce. Serve on buns topped with coleslaw.",
    ],
  },
  {
    title: "Mac and Cheese",
    description:
      "Ultra-creamy stovetop mac and cheese with a sharp cheddar blend.",
    imageSearch: "creamy mac and cheese cheddar",
    servings: 6,
    prepTime: 10,
    cookTime: 20,
    totalTime: 30,
    difficulty: "beginner",
    cuisine: "american",
    dietaryTags: ["vegetarian"],
    timeCategory: "quick",
    calories: 480,
    protein: 20,
    carbs: 42,
    fat: 24,
    ingredients: [
      { ingredient: "elbow macaroni", amount: "1 lb" },
      { ingredient: "sharp cheddar", amount: "3 cups shredded" },
      { ingredient: "whole milk", amount: "2.5 cups" },
      { ingredient: "butter", amount: "3 tbsp" },
      { ingredient: "flour", amount: "3 tbsp" },
      { ingredient: "Dijon mustard", amount: "1 tsp" },
      { ingredient: "paprika", amount: "1/2 tsp" },
      { ingredient: "salt and pepper", amount: "to taste" },
    ],
    instructions: [
      "Cook macaroni until al dente (1 minute less than package). Drain.",
      "Melt butter over medium heat. Whisk in flour and cook 1 minute.",
      "Gradually whisk in milk. Cook, stirring, until sauce thickens (about 5 minutes).",
      "Remove from heat. Stir in cheddar, mustard, and paprika until smooth.",
      "Fold in cooked pasta. Season and serve immediately.",
    ],
  },
  {
    title: "New England Clam Chowder",
    description:
      "Thick and creamy chowder loaded with clams, potatoes, and bacon.",
    imageSearch: "new england clam chowder bowl",
    servings: 6,
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    difficulty: "intermediate",
    cuisine: "american",
    dietaryTags: [],
    timeCategory: "moderate",
    calories: 380,
    protein: 18,
    carbs: 32,
    fat: 20,
    ingredients: [
      { ingredient: "canned clams", amount: "3 cans (6.5 oz each)" },
      { ingredient: "bacon", amount: "6 slices" },
      { ingredient: "Yukon Gold potatoes", amount: "1.5 lbs" },
      { ingredient: "onion", amount: "1 large" },
      { ingredient: "celery", amount: "2 stalks" },
      { ingredient: "heavy cream", amount: "1 cup" },
      { ingredient: "butter", amount: "2 tbsp" },
      { ingredient: "flour", amount: "3 tbsp" },
      { ingredient: "bay leaves", amount: "2" },
      { ingredient: "fresh thyme", amount: "1 tsp" },
    ],
    instructions: [
      "Drain clams, reserving liquid. Add water to clam juice to make 3 cups.",
      "Cook diced bacon until crispy. Remove and set aside.",
      "In bacon fat, sauté onion and celery. Add butter and flour, cook 2 minutes.",
      "Gradually add clam juice mixture. Add diced potatoes and bay leaves.",
      "Simmer 15-20 minutes until potatoes are tender.",
      "Add cream and clams. Heat through (don't boil). Season with thyme.",
      "Serve topped with crumbled bacon and oyster crackers.",
    ],
  },
  {
    title: "Avocado Toast with Everything Seasoning",
    description:
      "The modern classic — creamy avocado on crispy sourdough with a jammy egg.",
    imageSearch: "avocado toast egg sourdough",
    servings: 2,
    prepTime: 5,
    cookTime: 5,
    totalTime: 10,
    difficulty: "beginner",
    cuisine: "american",
    dietaryTags: ["vegetarian"],
    timeCategory: "quick",
    calories: 320,
    protein: 12,
    carbs: 28,
    fat: 18,
    ingredients: [
      { ingredient: "sourdough bread", amount: "2 slices" },
      { ingredient: "ripe avocado", amount: "1" },
      { ingredient: "eggs", amount: "2" },
      { ingredient: "everything bagel seasoning", amount: "1 tsp" },
      { ingredient: "red pepper flakes", amount: "pinch" },
      { ingredient: "lemon juice", amount: "1 tsp" },
    ],
    instructions: [
      "Toast sourdough until golden and crispy.",
      "Boil eggs for 6.5 minutes for jammy yolks. Ice bath immediately.",
      "Mash avocado with lemon juice and salt. Spread thickly on toast.",
      "Halve the egg on top. Sprinkle with everything seasoning and red pepper flakes.",
    ],
  },
  {
    title: "Overnight Oats",
    description:
      "No-cook make-ahead breakfast — creamy oats with your choice of toppings.",
    imageSearch: "overnight oats berries jar",
    servings: 2,
    prepTime: 5,
    cookTime: 0,
    totalTime: 5,
    difficulty: "beginner",
    cuisine: "american",
    dietaryTags: ["vegetarian", "gluten-free"],
    timeCategory: "quick",
    calories: 340,
    protein: 12,
    carbs: 52,
    fat: 10,
    ingredients: [
      { ingredient: "rolled oats", amount: "1 cup" },
      { ingredient: "milk or plant milk", amount: "1 cup" },
      { ingredient: "Greek yogurt", amount: "1/2 cup" },
      { ingredient: "chia seeds", amount: "1 tbsp" },
      { ingredient: "maple syrup", amount: "1 tbsp" },
      { ingredient: "vanilla extract", amount: "1/2 tsp" },
      { ingredient: "mixed berries", amount: "1/2 cup" },
    ],
    instructions: [
      "Combine oats, milk, yogurt, chia seeds, maple syrup, and vanilla in a jar.",
      "Stir well, cover, and refrigerate overnight (or at least 4 hours).",
      "In the morning, stir and top with berries, nuts, or any toppings you like.",
    ],
  },
  {
    title: "Grilled Salmon with Mango Salsa",
    description:
      "Perfectly grilled salmon fillet topped with bright, fresh mango salsa.",
    imageSearch: "grilled salmon mango salsa",
    servings: 4,
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    difficulty: "beginner",
    cuisine: "american",
    dietaryTags: ["gluten-free", "dairy-free"],
    timeCategory: "quick",
    calories: 360,
    protein: 34,
    carbs: 16,
    fat: 18,
    ingredients: [
      { ingredient: "salmon fillets", amount: "4 (6 oz each)" },
      { ingredient: "mango", amount: "1 large, diced" },
      { ingredient: "red onion", amount: "1/4 cup diced" },
      { ingredient: "jalapeño", amount: "1 small" },
      { ingredient: "cilantro", amount: "3 tbsp" },
      { ingredient: "lime", amount: "2" },
      { ingredient: "olive oil", amount: "1 tbsp" },
    ],
    instructions: [
      "Make salsa: combine diced mango, red onion, jalapeño, cilantro, and lime juice.",
      "Pat salmon dry. Brush with oil and season with salt and pepper.",
      "Grill skin-side down 4-5 minutes. Flip and cook 3-4 more minutes.",
      "Serve salmon topped with a generous spoonful of mango salsa.",
    ],
  },
  {
    title: "Stuffed Bell Peppers",
    description:
      "Colorful peppers filled with seasoned ground turkey, rice, and cheese.",
    imageSearch: "stuffed bell peppers cheese",
    servings: 4,
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    difficulty: "intermediate",
    cuisine: "american",
    dietaryTags: ["gluten-free"],
    timeCategory: "moderate",
    calories: 380,
    protein: 28,
    carbs: 32,
    fat: 16,
    ingredients: [
      { ingredient: "bell peppers", amount: "4 large" },
      { ingredient: "ground turkey", amount: "1 lb" },
      { ingredient: "cooked rice", amount: "1 cup" },
      { ingredient: "diced tomatoes", amount: "1 can" },
      { ingredient: "onion", amount: "1" },
      { ingredient: "garlic", amount: "2 cloves" },
      { ingredient: "Mexican cheese blend", amount: "1 cup" },
      { ingredient: "cumin", amount: "1 tsp" },
      { ingredient: "chili powder", amount: "1 tsp" },
    ],
    instructions: [
      "Preheat oven to 375°F. Cut tops off peppers and remove seeds.",
      "Brown turkey with diced onion and garlic. Drain excess fat.",
      "Stir in rice, diced tomatoes, cumin, chili powder, and half the cheese.",
      "Stuff peppers with the filling. Place in a baking dish with a splash of water.",
      "Cover with foil, bake 25 minutes. Remove foil, top with cheese, bake 10 more minutes.",
    ],
  },
  {
    title: "Garlic Butter Steak Bites",
    description:
      "Juicy cubed steak tossed in garlic herb butter — ready in 15 minutes.",
    imageSearch: "garlic butter steak bites herbs",
    servings: 4,
    prepTime: 5,
    cookTime: 10,
    totalTime: 15,
    difficulty: "beginner",
    cuisine: "american",
    dietaryTags: ["keto", "gluten-free"],
    timeCategory: "quick",
    calories: 380,
    protein: 36,
    carbs: 2,
    fat: 26,
    ingredients: [
      { ingredient: "sirloin steak", amount: "2 lbs" },
      { ingredient: "butter", amount: "3 tbsp" },
      { ingredient: "garlic", amount: "5 cloves" },
      { ingredient: "fresh thyme", amount: "1 tbsp" },
      { ingredient: "fresh rosemary", amount: "1 tbsp" },
      { ingredient: "olive oil", amount: "1 tbsp" },
    ],
    instructions: [
      "Cut steak into 1-inch cubes. Season generously with salt and pepper.",
      "Heat olive oil in a cast iron skillet over high heat until smoking.",
      "Add steak in a single layer. Sear 2 minutes without moving, then flip.",
      "Add butter, garlic, thyme, and rosemary. Baste steak with melted garlic butter for 1 minute.",
      "Remove from heat immediately. Residual heat will finish cooking to medium-rare.",
    ],
  },
  {
    title: "Fluffy Buttermilk Pancakes",
    description:
      "Thick, fluffy pancakes with real buttermilk and vanilla — a weekend staple.",
    imageSearch: "fluffy buttermilk pancakes maple syrup",
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    difficulty: "beginner",
    cuisine: "american",
    dietaryTags: ["vegetarian"],
    timeCategory: "quick",
    calories: 320,
    protein: 8,
    carbs: 44,
    fat: 12,
    ingredients: [
      { ingredient: "all-purpose flour", amount: "1.5 cups" },
      { ingredient: "buttermilk", amount: "1.25 cups" },
      { ingredient: "egg", amount: "1" },
      { ingredient: "butter (melted)", amount: "3 tbsp" },
      { ingredient: "sugar", amount: "2 tbsp" },
      { ingredient: "baking powder", amount: "1.5 tsp" },
      { ingredient: "baking soda", amount: "1/2 tsp" },
      { ingredient: "vanilla extract", amount: "1 tsp" },
      { ingredient: "maple syrup", amount: "for serving" },
    ],
    instructions: [
      "Whisk flour, sugar, baking powder, baking soda, and salt.",
      "In another bowl, whisk buttermilk, egg, melted butter, and vanilla.",
      "Pour wet into dry and stir until just combined. Lumps are fine.",
      "Heat a griddle over medium heat. Ladle 1/4 cup batter per pancake.",
      "Cook until bubbles form and edges set (about 2 minutes). Flip, cook 1 more minute.",
      "Serve with butter and warm maple syrup.",
    ],
  },

  // ---------- MIDDLE EASTERN ----------
  {
    title: "Chicken Shawarma",
    description:
      "Warmly spiced chicken with garlic sauce, served in pita or over rice.",
    imageSearch: "chicken shawarma pita wrap",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "intermediate",
    cuisine: "middle-eastern",
    dietaryTags: ["dairy-free"],
    timeCategory: "moderate",
    calories: 380,
    protein: 34,
    carbs: 12,
    fat: 22,
    ingredients: [
      { ingredient: "chicken thighs", amount: "2 lbs boneless" },
      { ingredient: "cumin", amount: "2 tsp" },
      { ingredient: "coriander", amount: "1 tsp" },
      { ingredient: "turmeric", amount: "1 tsp" },
      { ingredient: "paprika", amount: "2 tsp" },
      { ingredient: "cinnamon", amount: "1/2 tsp" },
      { ingredient: "lemon", amount: "1" },
      { ingredient: "garlic", amount: "6 cloves" },
      { ingredient: "olive oil", amount: "3 tbsp" },
      { ingredient: "pita bread", amount: "4" },
      { ingredient: "tahini", amount: "3 tbsp" },
    ],
    instructions: [
      "Mix all spices with olive oil, lemon juice, and minced garlic into a marinade.",
      "Coat chicken and marinate at least 1 hour (overnight is best).",
      "Cook chicken 5-6 minutes per side until charred and cooked through.",
      "Let rest 5 minutes, then slice thin against the grain.",
      "Make tahini sauce: whisk tahini with lemon juice, garlic, and water.",
      "Serve in pita with pickled onions, tomatoes, and tahini sauce.",
    ],
  },
  {
    title: "Hummus from Scratch",
    description:
      "Silky smooth hummus with extra tahini and a cumin-paprika oil drizzle.",
    imageSearch: "homemade hummus olive oil paprika",
    servings: 6,
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    difficulty: "beginner",
    cuisine: "middle-eastern",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "quick",
    calories: 180,
    protein: 8,
    carbs: 18,
    fat: 10,
    ingredients: [
      { ingredient: "canned chickpeas", amount: "2 cans (15 oz each)" },
      { ingredient: "tahini", amount: "1/3 cup" },
      { ingredient: "lemon juice", amount: "3 tbsp" },
      { ingredient: "garlic", amount: "2 cloves" },
      { ingredient: "ice water", amount: "3-4 tbsp" },
      { ingredient: "cumin", amount: "1/2 tsp" },
      { ingredient: "olive oil", amount: "2 tbsp" },
      { ingredient: "paprika", amount: "for garnish" },
    ],
    instructions: [
      "Drain chickpeas. For extra smooth hummus, rub them to remove skins.",
      "Blend tahini and lemon juice for 1 minute until thick and creamy.",
      "Add garlic, cumin, and salt. Blend 30 seconds.",
      "Add chickpeas and blend 1 minute. Drizzle in ice water until silky smooth.",
      "Spread on a plate, drizzle with olive oil and paprika.",
    ],
  },
  {
    title: "Baba Ganoush",
    description: "Smoky roasted eggplant dip with tahini and lemon.",
    imageSearch: "baba ganoush eggplant dip",
    servings: 4,
    prepTime: 10,
    cookTime: 40,
    totalTime: 50,
    difficulty: "beginner",
    cuisine: "middle-eastern",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "moderate",
    calories: 120,
    protein: 3,
    carbs: 12,
    fat: 8,
    ingredients: [
      { ingredient: "eggplants", amount: "2 large" },
      { ingredient: "tahini", amount: "2 tbsp" },
      { ingredient: "lemon juice", amount: "2 tbsp" },
      { ingredient: "garlic", amount: "2 cloves" },
      { ingredient: "olive oil", amount: "2 tbsp" },
      { ingredient: "smoked paprika", amount: "1/2 tsp" },
      { ingredient: "fresh parsley", amount: "for garnish" },
    ],
    instructions: [
      "Prick eggplants all over. Roast at 425°F for 40 minutes until completely collapsed.",
      "Let cool slightly, then scoop out the flesh. Discard skin.",
      "Mash eggplant (keep it chunky) with tahini, lemon juice, garlic, and salt.",
      "Spread on a plate, drizzle with olive oil, sprinkle smoked paprika and parsley.",
    ],
  },
  {
    title: "Tabbouleh",
    description:
      "Fresh herb-forward salad with bulgur, parsley, mint, and tomatoes.",
    imageSearch: "tabbouleh salad parsley mint",
    servings: 4,
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    difficulty: "beginner",
    cuisine: "middle-eastern",
    dietaryTags: ["vegan", "dairy-free"],
    timeCategory: "quick",
    calories: 160,
    protein: 4,
    carbs: 24,
    fat: 6,
    ingredients: [
      { ingredient: "bulgur wheat", amount: "1/2 cup" },
      { ingredient: "fresh parsley", amount: "2 cups finely chopped" },
      { ingredient: "fresh mint", amount: "1/2 cup chopped" },
      { ingredient: "tomatoes", amount: "3 diced" },
      { ingredient: "cucumber", amount: "1 diced" },
      { ingredient: "green onions", amount: "3" },
      { ingredient: "lemon juice", amount: "1/4 cup" },
      { ingredient: "olive oil", amount: "3 tbsp" },
    ],
    instructions: [
      "Soak bulgur in boiling water for 10 minutes. Drain and squeeze dry.",
      "Combine with parsley, mint, tomatoes, cucumber, and green onions.",
      "Dress with lemon juice, olive oil, salt, and pepper.",
      "Let sit 15 minutes for flavors to meld. Serve at room temperature.",
    ],
  },

  // ---------- FRENCH ----------
  {
    title: "French Onion Soup",
    description:
      "Deeply caramelized onion soup topped with a crusty Gruyère crouton.",
    imageSearch: "french onion soup gruyere bread",
    servings: 4,
    prepTime: 15,
    cookTime: 75,
    totalTime: 90,
    difficulty: "advanced",
    cuisine: "french",
    dietaryTags: [],
    timeCategory: "elaborate",
    calories: 380,
    protein: 16,
    carbs: 34,
    fat: 20,
    ingredients: [
      { ingredient: "yellow onions", amount: "4 large" },
      { ingredient: "butter", amount: "3 tbsp" },
      { ingredient: "beef broth", amount: "6 cups" },
      { ingredient: "dry white wine", amount: "1/2 cup" },
      { ingredient: "fresh thyme", amount: "4 sprigs" },
      { ingredient: "bay leaf", amount: "1" },
      { ingredient: "baguette", amount: "1" },
      { ingredient: "Gruyère cheese", amount: "2 cups shredded" },
    ],
    instructions: [
      "Thinly slice all onions. Melt butter in a Dutch oven over medium heat.",
      "Add onions with salt. Cook slowly, stirring occasionally, for 45-60 minutes until deep golden. Don't rush.",
      "Deglaze with white wine, scraping up fond. Cook until wine evaporates.",
      "Add beef broth, thyme, and bay leaf. Simmer 20 minutes.",
      "Ladle soup into oven-safe bowls. Top with toasted baguette slice.",
      "Pile Gruyère on top. Broil until cheese is bubbly and golden, about 3 minutes.",
    ],
  },
  {
    title: "Classic Crêpes",
    description: "Thin French pancakes — fill them sweet or savory.",
    imageSearch: "french crepes nutella berries",
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    totalTime: 30,
    difficulty: "intermediate",
    cuisine: "french",
    dietaryTags: ["vegetarian"],
    timeCategory: "moderate",
    calories: 220,
    protein: 8,
    carbs: 28,
    fat: 8,
    ingredients: [
      { ingredient: "all-purpose flour", amount: "1 cup" },
      { ingredient: "eggs", amount: "2" },
      { ingredient: "whole milk", amount: "1 cup" },
      { ingredient: "water", amount: "1/2 cup" },
      { ingredient: "butter (melted)", amount: "2 tbsp" },
      { ingredient: "sugar", amount: "1 tbsp" },
      { ingredient: "vanilla extract", amount: "1 tsp" },
      { ingredient: "salt", amount: "pinch" },
    ],
    instructions: [
      "Blend flour, eggs, milk, water, melted butter, sugar, vanilla, and salt until smooth. Rest 30 minutes.",
      "Heat a non-stick pan over medium heat. Lightly butter the surface.",
      "Pour about 3 tbsp batter, immediately swirling to coat evenly.",
      "Cook 1-2 minutes until edges lift. Flip and cook 30 seconds more.",
      "Fill with Nutella and bananas, lemon and sugar, or ham and cheese.",
    ],
  },
  {
    title: "Ratatouille",
    description:
      "Provençal vegetable stew with eggplant, zucchini, and tomatoes.",
    imageSearch: "ratatouille vegetable provencal",
    servings: 4,
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    difficulty: "intermediate",
    cuisine: "french",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    timeCategory: "elaborate",
    calories: 180,
    protein: 4,
    carbs: 22,
    fat: 10,
    ingredients: [
      { ingredient: "eggplant", amount: "1 large" },
      { ingredient: "zucchini", amount: "2 medium" },
      { ingredient: "yellow squash", amount: "1" },
      { ingredient: "Roma tomatoes", amount: "4" },
      { ingredient: "red bell pepper", amount: "1" },
      { ingredient: "onion", amount: "1" },
      { ingredient: "garlic", amount: "4 cloves" },
      { ingredient: "tomato sauce", amount: "1 cup" },
      { ingredient: "fresh basil and thyme", amount: "2 tbsp each" },
      { ingredient: "olive oil", amount: "3 tbsp" },
    ],
    instructions: [
      "Preheat oven to 375°F. Dice onion, bell pepper, and garlic.",
      "Sauté onion and pepper until soft. Add garlic and cook 1 minute.",
      "Spread tomato sauce in the bottom of a baking dish.",
      "Slice eggplant, zucchini, squash, and tomatoes into thin rounds.",
      "Arrange vegetable slices in alternating layers standing upright.",
      "Drizzle with olive oil, season with salt, pepper, and thyme.",
      "Cover with foil, bake 40 minutes. Uncover, bake 15 more minutes. Top with fresh basil.",
    ],
  },
  {
    title: "Beef Wellington",
    description:
      "Seared beef tenderloin wrapped in mushroom duxelles and golden puff pastry.",
    imageSearch: "beef wellington puff pastry",
    servings: 6,
    prepTime: 45,
    cookTime: 30,
    totalTime: 75,
    difficulty: "advanced",
    cuisine: "french",
    dietaryTags: [],
    timeCategory: "elaborate",
    calories: 620,
    protein: 42,
    carbs: 28,
    fat: 36,
    ingredients: [
      { ingredient: "beef tenderloin", amount: "2.5 lbs center-cut" },
      { ingredient: "puff pastry", amount: "1 sheet" },
      { ingredient: "mushrooms", amount: "1 lb" },
      { ingredient: "prosciutto", amount: "8 slices" },
      { ingredient: "Dijon mustard", amount: "2 tbsp" },
      { ingredient: "egg yolk", amount: "1" },
      { ingredient: "shallots", amount: "2" },
      { ingredient: "fresh thyme", amount: "1 tbsp" },
      { ingredient: "garlic", amount: "3 cloves" },
    ],
    instructions: [
      "Sear tenderloin on all sides until deeply browned. Brush with Dijon mustard. Chill.",
      "Pulse mushrooms, shallots, and garlic until fine. Cook until all moisture evaporates (duxelles). Cool.",
      "Overlap prosciutto on plastic wrap. Spread mushroom duxelles on top.",
      "Place beef on edge and roll tightly. Chill 30 minutes.",
      "Roll out puff pastry. Unwrap beef, place on pastry. Roll up and seal edges. Egg wash.",
      "Bake at 425°F for 25-30 minutes until golden and internal temp reaches 125°F.",
      "Rest 10 minutes before slicing.",
    ],
  },
  {
    title: "Chocolate Lava Cake",
    description:
      "Individual molten chocolate cakes with a gooey, liquid center.",
    imageSearch: "chocolate lava cake molten",
    servings: 4,
    prepTime: 15,
    cookTime: 12,
    totalTime: 27,
    difficulty: "intermediate",
    cuisine: "french",
    dietaryTags: ["vegetarian"],
    timeCategory: "quick",
    calories: 380,
    protein: 6,
    carbs: 32,
    fat: 26,
    ingredients: [
      { ingredient: "dark chocolate (70%)", amount: "6 oz" },
      { ingredient: "butter", amount: "1/2 cup" },
      { ingredient: "eggs", amount: "2 whole + 2 yolks" },
      { ingredient: "sugar", amount: "1/4 cup" },
      { ingredient: "flour", amount: "2 tbsp" },
      { ingredient: "vanilla extract", amount: "1 tsp" },
      { ingredient: "cocoa powder", amount: "for dusting" },
    ],
    instructions: [
      "Preheat oven to 425°F. Butter 4 ramekins and dust with cocoa powder.",
      "Melt chocolate and butter together.",
      "Whisk eggs, yolks, and sugar until thick and pale. Fold in chocolate mixture.",
      "Fold in flour gently. Divide among ramekins.",
      "Bake exactly 12-13 minutes. Edges set, center jiggles.",
      "Rest 1 minute, then invert onto plates. Center should ooze when cut.",
    ],
  },
];

// ============================================
// SEED SCRIPT WITH IMAGE UPLOAD
// ============================================
async function seed() {
  console.log("🌱 Seeding recipe database with images...\n");

  let successCount = 0;
  let imageFailCount = 0;

  for (let i = 0; i < recipes.length; i++) {
    const recipe = recipes[i];
    console.log(`[${i + 1}/${recipes.length}] ${recipe.title}`);

    // Step 1: Fetch image from Pexels
    let imageUrl: string | null = null;
    const pexelsResult = await fetchPexelsImage(recipe.imageSearch);

    if (pexelsResult) {
      // Step 2: Upload to UploadThing
      const slug = recipe.title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "");
      imageUrl = await uploadToUploadThing(pexelsResult.url, `seed-${slug}`);

      if (imageUrl) {
        console.log(
          `  📸 Image uploaded (credit: ${pexelsResult.photographer})`,
        );
      } else {
        console.log(`  ⚠️  Image upload failed, continuing without image`);
        imageFailCount++;
      }
    } else {
      console.log(`  ⚠️  No image found, continuing without image`);
      imageFailCount++;
    }

    // Step 3: Insert recipe
    const [inserted] = await db
      .insert(seedRecipes)
      .values({
        title: recipe.title,
        description: recipe.description,
        imageUrl,
        servings: recipe.servings,
        prepTime: recipe.prepTime,
        cookTime: recipe.cookTime,
        totalTime: recipe.totalTime,
        difficulty: recipe.difficulty,
        cuisine: recipe.cuisine,
        dietaryTags: recipe.dietaryTags,
        timeCategory: recipe.timeCategory,
        calories: recipe.calories,
        protein: recipe.protein,
        carbs: recipe.carbs,
        fat: recipe.fat,
      })
      .returning({ id: seedRecipes.id });

    // Step 4: Insert ingredients
    if (recipe.ingredients.length > 0) {
      await db.insert(seedRecipeIngredients).values(
        recipe.ingredients.map((ing, idx) => ({
          seedRecipeId: inserted.id,
          ingredient: ing.ingredient,
          amount: ing.amount,
          order: idx + 1,
        })),
      );
    }

    // Step 5: Insert instructions
    if (recipe.instructions.length > 0) {
      await db.insert(seedRecipeInstructions).values(
        recipe.instructions.map((step, idx) => ({
          seedRecipeId: inserted.id,
          step,
          order: idx + 1,
        })),
      );
    }

    console.log(`  ✅ Saved to database`);
    successCount++;

    // Rate limit: wait between Pexels API calls
    await sleep(250);
  }

  console.log(`\n🎉 Done! ${successCount} recipes seeded.`);
  if (imageFailCount > 0) {
    console.log(
      `⚠️  ${imageFailCount} recipes without images (can be added later).`,
    );
  }
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
